In [1]:
# Setup (Set working directory, paths, and random seeds)
# Load modules
import os                    # working directory 
import subprocess            # git clone
import sys                   # check Colab
from pathlib import Path     # paths

# Set working directory (w/ git clone)
IN_COLAB = 'google.colab' in sys.modules or Path('/content').exists()

if IN_COLAB:
    ROOT = Path('/content/dl_practice')
    if not ROOT.exists(): 
        subprocess.run(['git', 'clone', 'https://github.com/seungyong0223/dl_practice', str(ROOT) ])
    os.chdir(ROOT)
else:
    if '__file__' in dir(): 
        ROOT = Path(__file__).resolve().parents[1]
    else: 
        ROOT = Path.cwd()
    os.chdir(ROOT)
    
print(f"Working directory is {ROOT}")

# Define paths 
DATA_DIR = ROOT / "data"
CKPT_DIR = ROOT / "checkpoints"
OUTPUT_DIR = ROOT / "outputs"

for d in [DATA_DIR, CKPT_DIR, OUTPUT_DIR]:
    d.mkdir(parents=True, exist_ok=True)
    
# Set random seeds 
SEED = 1

import random
import numpy as np 
import torch 

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# Check CPU/GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Current Device is {device}")


Working directory is /content/dl_practice
Current Device is cuda


In [3]:
# Load modules 
import torch 
import numpy 


In [4]:
# Initializing a Tensor 

# From data 
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor 1: \n {x_data} \n")

# From a Numpy array
np_array = np.array(data) 
x_np = torch.from_numpy(np_array)
print(f"Tensor 2: \n {x_np} \n")

# From another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
 
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Tensor 1: 
 tensor([[1, 2],
        [3, 4]]) 

Tensor 2: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]]) 



In [5]:
# Tensors with random or constant values

shape = (2, 3)  # a tuple of tensor dimensions 
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.0293, 0.7999, 0.3971],
        [0.7544, 0.5695, 0.4388]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
# Attributes of a Tensor 
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
# Operations on Tensors 

# Move tensors to the accelerator 
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

# Numpy-like indexing and slicing
tensor = torch.ones(4, 4) 
tensor[:,1] = 0
print(f"Indexing and Slicing: \n {tensor} \n") 

# Joining 
t1 = torch.cat([tensor, tensor, tensor], dim=1) 
print(f"Joining: \n {t1} \n") 

# Element-wise product
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor: \n {tensor * tensor} \n")

# Matrix multiplication 
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")


Device tensor is stored on: cuda:0
Indexing and Slicing: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

Joining: 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [ ]:
# In-place operations 
# Note that it is problematic when computing gradients 
print(tensor, "\n")
tensor.add_(5)
print(tensor, "\n")


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [34]:
# Tensor & NumPy 
# Tensors on the CPU and NumPy arrays can share their memory locations. 
# Changing one will change the oher. 

# Tensor to NumPy array
t = torch.ones(5) 
n = t.numpy() 
print("\n Tensors to NumPy \n")
print(f"t: {t}")
print(f"n: {n}")

# add 
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# NumPy array to Tensor 
n = np.ones(5) 
t = torch.from_numpy(n)
print("\n NumPy to Tensor \n")
print(f"t: {t}")
print(f"n: {n}")

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")



 Tensors to NumPy 

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]

 NumPy to Tensor 

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
